import Header from './Components/Header'
import './globals.scss'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight: "700" })

export const metadata = {
  title: 'Netflix',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}><Header />{children}</body>
    </html>
  )
}
